### PR TITLE
Add Actions

### PR DESCRIPTION
**Pull request by dbrumley**

### CODE REVIEW

**Comment by dbrumley** [comment]
This PR:
* Added github actions to build the code in github actions and upload the build artifact. You can find the created html under the github action run
* Adds a reference to Xeno Kovah (CMU alumni)'s course on x86-64 training in the assembly section.

**Comment by syreal17** [comment]
I've already added a reference to Xeno Kovah's class at the end of the assembly chapter. I don't mind merging in your reference too, since it happens at the beginning of the chapter.

I'm still new to GitHub Actions, where does the artifact upload deposit the copy of book.html? Right now, the manual work flow is: build using asciidoctor on a separate machine (version on primer.picoctf.org renders incorrect syntax highlighting) upload with scp to `/var/www/html/book/book.html`. It seems like the artifact update action isn't updating to the correct path.

**Comment by dbrumley** [comment]
The artifact is uploaded as part of the action.  Screen shot attached. let me know if you still can't find them.
Screen Shot 2022-01-18 at 9 30 09 AM

**Comment by syreal17** [comment]
Ok, thanks! Looks good!

**Pull request merged**
